【WIP】chore(fix-dialog-layout): ダイアログ ボタン配置変更
n-air-app/n-air-app pull request #220
Opened 2018-12-13 12:12 UTC by hiroshi-takezawa

**このpull requestが解決する内容**
#125 のPRです。

**動作確認手順**
https://atl.dwango.co.jp/confluence/pages/viewpage.action?pageId=161376870

2018-12-13 12:23 UTC, hiroshi-takezawa commented
- ダイアログ1(以下添付のようなタイプ)のボタンは、配置しか変わっていない。(機能が逆のまま)
- 改修方法を確認したい
<img width="300" alt="2018-12-13 21 19 00" src="https://user-images.githubusercontent.com/43235607/49938274-bd021e80-ff1c-11e8-9d5b-9cde06873bd3.png">


- 「アンケートに答えずに配信ツールを終了した時のダイアログ」の表示方法  要確認
(アンケートは30日後に表示される)

2018-12-18 05:59 UTC, berlysia commented
ダイアログ1の形式について、機能が変更できていないのは、押されたボタンの位置を使ってそのあとの処理が書かれているからですね。
[dialog.showMessageBox](https://electronjs.org/docs/api/dialog#dialogshowmessageboxbrowserwindow-options-callback) の説明をざっと読むと直せると思います。

2018-12-19 02:05 UTC, takezawahiroshi commented
> dialog.showMessageBox の説明をざっと読むと直せると思います。

確認します :raising_hand:

2018-12-28 05:35 UTC, hiroshi-takezawa commented
![dialog-1228-1](https://user-images.githubusercontent.com/43235607/50503968-c3ac9c00-0aad-11e9-94ab-9f9ed06a81a6.gif)

2018-12-28 05:43 UTC, hiroshi-takezawa commented
![dialog-1228-2](https://user-images.githubusercontent.com/43235607/50504141-decbdb80-0aae-11e9-8886-dec8e11e9807.gif)

2019-02-08 07:32 UTC, koizuka requested changes

2019-02-08 07:32 UTC, koizuka commented on app/services/questionaire.ts
> +            buttons: [$t('common.ok'), $t('common.cancel'), ],
ここの入れ替え結果のokの論理が下で反転されてない

2024-09-02 08:09 UTC, koizuka commented
ModalLayoutのshowCancelの部分は直していないものの、showCancelをつけてる利用がなく、それ以外は #776 で解決してるのでcloseします

2024-09-02 08:09 UTC, closed without merging