番組URLをクリップボードへコピーする機能を番組情報パネルに追加
n-air-app/n-air-app pull request #301
Opened 2019-05-10 09:35 UTC by takayamaki

**このpull requestが解決する内容**
ニコ生エリアに番組URLをクリップボードへコピーするリンクを追加し、ワンクリックで番組URLをクリップボードへコピーできるようにします。

![image](https://user-images.githubusercontent.com/24884114/57516025-dd5cca80-734e-11e9-9e50-27a1324a7aca.png)

**背景**
- ニコ生と連携するツールなどで使用するために、番組URLが必要となる場合がある
- 番組タイトルやtwitterシェアボタンをクリックすると既定のブラウザでwatch画面やtwitterのShare画面が出るため、そのアドレスバーや投稿欄からコピーできるといえばできる
  - しかし、「番組タイトルまたはtwitterシェアボタンをクリックし、既定のブラウザが起動するのを待ち、アドレスを選択し、コピーする」という4アクションが必要であり非常に煩雑
- したがって、N Air上での1アクションで番組URLをクリップボードへコピーできるようにしたい

**検討、ブラッシュアップの余地がある点**
- 追加する先はトップナビで良いのか
- クリップボードへ番組URLをコピーした際に視覚的フィードバックがない

**動作確認手順**
1. N Airから番組を作成、または既存番組を取得する
1. 番組情報のトップナビ部にある「番組URLをコピー」をクリックする
1. クリップボードへニコ生のURLがコピーされていることを確認する

2019-05-22 12:25 UTC, berlysia commented
https://github.com/n-air-app/n-air-app/issues/300 で後から対応すると記録したので、一旦これで行っちゃって構わないみたいな話だった気がしますが、どうでしたっけ

2019-05-24 10:11 UTC, berlysia approved these changes

2019-05-24 10:19 UTC, berlysia requested changes
（すみません後から気づきました）

2019-05-24 10:19 UTC, berlysia commented on app/components/nicolive-area/TopNav.vue
> +        <a @click="copyProgramURL" :disabled="isFetching" class="link"><i class="icon-clipboard-copy"></i>番組URLをコピー</a>
:memo: isFetchingは正しいのかな、と思ったけどそもそもa要素にdisabled指定してるのがおかしいですね。
外観当てたときに自分がレビューで見逃していたようだ

この変更に関して、disabledの部分を削除してもらえますか。hasProgramがtrueなら番組URLはコピーできるはずなので。

2019-05-24 10:28 UTC, takayamaki commented on app/components/nicolive-area/TopNav.vue
> +        <a @click="copyProgramURL" :disabled="isFetching" class="link"><i class="icon-clipboard-copy"></i>番組URLをコピー</a>
特に強い理由はなくて周りに合わせただけなので、そうであればそのようにしますー

2019-05-29 11:15 UTC, berlysia approved these changes
反映ありがとうございます:sparkles:

2019-05-29 11:41 UTC, merged