up to webpack5 and binary libs
n-air-app/n-air-app pull request #657
Opened 2023-05-08 05:07 UTC by asaday

# このpull requestが解決する内容

webpack5へのアップデート (#648) 及び obs バイナリのアップデート (#646) のmix版 
両方を同時に検証する場合はこちらで。
片方ずつ行うならそれぞれで行ってください。

# 動作確認手順

通常通り

# 関連するIssue（あれば）

2023-05-09 09:05 UTC, koizuka commented on .vscode/settings.json
> +  "workbench.colorCustomizations": {
このブランチをcheckoutするとVS Codeの色が変わってしまうけど、どういう目的だろうか

2023-05-09 09:15 UTC, asaday commented on .vscode/settings.json
> +  "workbench.colorCustomizations": {
あ、これは完全にこちらのデバッグ都合の名残りですね。戻します

2023-05-15 08:25 UTC, koizuka commented
ブレンドモード試したけど良い感じに動いてそう :+1:

2023-06-14 04:59 UTC, koizuka commented on app/components/obs/inputs/ObsInput.ts
> +        info: obsProp.details.type === obs.ETextType.TextInfo,
メモ: OBS設定項目に説明表示だけのタイプが追加されたのに対応している

2023-06-14 05:00 UTC, koizuka commented on app/components/obs/inputs/ObsEditableListInput.vue.ts
> +    if (filePaths && filePaths.length) {
メモ: 画像スライドで使われている、ファイルリストの入力ダイアログの戻りの処理漏れの修正

2023-06-14 05:01 UTC, koizuka commented on app/components/obs/inputs/ObsTextInput.vue
> +    <div class="input-label" v-if="!value.info">
OBS設定項目に説明表示だけのタイプが追加されたのに対応している。 `value.info` で分岐

2023-06-14 05:04 UTC, koizuka commented on app/services/audio/audio.ts
> +      isControlledViaObs:
メモ:OBS(N Air)を通して音声を制御するフラグ反映

2023-06-14 05:04 UTC, koizuka commented on app/components/Mixer.vue.ts
> +      return !source.mixerHidden && source.isControlledViaObs;
メモ:OBS(N Air)を通して音声を制御するフラグ反映

2023-06-14 05:06 UTC, koizuka requested changes

2023-06-14 05:06 UTC, koizuka commented on test/helpers/spectron/index.ts
> +    t.context.app.client.timeouts('implicit', 2000); // CI環境で問題が出るので試しに時間追加>ローカルテストで落ちるので戻してみる
これは結局どうなったのかな? 解決したようならコメントを直して貰えると

2023-06-14 05:07 UTC, koizuka commented on app/components/tsx-component.ts
> +import Vue from 'vue';
メモ: Streamlabs側から新しいコンポーネントの仕組み(TSX)をバックポート

2023-06-14 05:09 UTC, koizuka requested changes

2023-06-14 05:09 UTC, koizuka commented on app/components/SourceSelector.vue.ts
> +  wasapi_process_output_capture: 'icon-display',
VLCソースとアプリ音声キャプチャのアイコンが仮当て

2023-06-14 05:09 UTC, asaday commented on test/helpers/spectron/index.ts
> +    t.context.app.client.timeouts('implicit', 2000); // CI環境で問題が出るので試しに時間追加>ローカルテストで落ちるので戻してみる
解決というよりは試してみて効果無し＆副作用が起きたってところですね。
不要なのでコメント自体消しますね

2023-06-14 05:13 UTC, koizuka commented on app/i18n/ja-JP/common.json
> +  "OBSInit.NotSupportedError": "OBSの初期化に失敗しました。ビデオドライバーが古すぎる、もしくはN Airがサポートしないシステムの可能性があります。",
```suggestion
  "OBSInit.NotSupportedError": "OBSの初期化に失敗しました。ビデオドライバーが古い、もしくはN Airがサポートしないシステムの可能性があります。",
```

2023-06-14 05:16 UTC, koizuka commented on app/components/windows/SourcesShowcase.vue
> +      <add-source-info
メモ: ソース追加画面でのアプリ音声キャプチャ部分

2023-06-14 05:16 UTC, koizuka commented on app/components/windows/SourcesShowcase.vue
> +      <add-source-info
メモ: ソース追加画面でのVLCキャプチャ部分

2023-06-14 05:17 UTC, koizuka commented on app/components/windows/BrowserSourceInteraction.tsx
> +import TsxComponent from 'components/tsx-component';
メモ: StreamlabsからWebページインタラクションをポート

2023-06-14 05:18 UTC, koizuka commented on app/util/menus/BlendingMethodMenu.ts
> +import { Menu } from './Menu';
メモ:ソースのブレンドモードのメニュー

2023-06-14 05:19 UTC, koizuka commented on app/util/menus/BlendingModeMenu.ts
> +import { Menu } from './Menu';
メモ:ソースのブレンドモードのメニュー

2023-06-14 05:20 UTC, koizuka commented on app/util/menus/ScaleFilteringMenu.ts
> +import { Menu } from './Menu';
メモ:ソースのスケールフィルタリンクのメニュー

2023-06-14 08:48 UTC, kechino approved these changes
CSS関係確認しました！

2023-06-14 09:49 UTC, yushinakatani approved these changes
英語も問題ないと思います

2023-06-15 02:24 UTC, yusukess approved these changes
スタイル部分のみ確認しました。

2023-06-15 03:38 UTC, taroc-dw commented on app/components/obs/inputs/Components.ts
>  const inputComponents = comps as any as { [key: string]: typeof Vue };
```suggestion
const inputComponents = comps as any as { [key: string]: typeof TsxComponent };
```

としておくと16行目の `as typeof TsxComponent` を外せそうです

2023-06-15 03:53 UTC, taroc-dw commented on app/i18n/ja-JP/sources.json
> +  "Darken": "ダーク",
比較(明)、比較(暗)という訳が一般的かなと思います
OBSもそうなってましたー
![スクリーンショット 2023-06-15 12 51 22](https://github.com/n-air-app/n-air-app/assets/105403669/11c80779-4cf5-49dc-b5d9-b784951a9556)

2023-06-15 08:15 UTC, taroc-dw commented on app/services/window-size.test.ts
> +    //@ts-ignore
こんな感じにすると `@ts-ignore` が外せそうです

```ts
const suiteList:  [PanelState | null, PanelState, boolean] = [
    [null, PanelState.INACTIVE, true],
    [null, PanelState.INACTIVE, false],
    [null, PanelState.CLOSED, true],
    [null, PanelState.CLOSED, false],
    [null, PanelState.OPENED, true],
    [null, PanelState.OPENED, false],
];

const initSuites: {
    prev: PanelState | null;
    next: PanelState;
    smallerThanMinWidth: boolean;
  }[] = suiteList.map(([prev, next, smallerThanMinWidth]) => ({
    prev,
    next,
    smallerThanMinWidth,
  }));
```

2023-06-15 08:23 UTC, taroc-dw commented on app/util/requests.ts
> +            reader.read().then(readStream as (value: ReadableStreamReadResult<any>) => void);
readStreamのvalueをオプショナルにすればas外せそうです

2023-06-15 08:32 UTC, taroc-dw commented on app/services/source-filters.ts
> +        type: type as TSourceFilterType,
`listItem.value` は `TSourceFilterType` 型のようなのでそちらを指定しても良いかと思いました

2023-06-26 12:19 UTC, matsuyuki-a commented on app/services/i18n/i18n.ts
> +  // @ts-ignore
差し支えなければ `@ts-expect-error` を使いたいのと、どのような型解決が困難だったかを書いておいた方がよさそうです。（あと、これがあるなら下の `as string` は不要なような気もします)

2023-06-26 12:20 UTC, matsuyuki-a commented on app/services/nicolive-program/NicoliveClient.ts
> +      return NicoliveClient.wrapFetchError(err as Error);
自分用のメモ: 後でここの型を確認する

2023-06-26 16:32 UTC, asaday commented on app/services/i18n/i18n.ts
> +  // @ts-ignore
これらは改修による変更に伴う際に回避したものではなく、tsconfig.jsonでのstrict系の設定変更において既存コードを極力変更しないように対応するため入れたものです。
strictではチェックの厳格化のみのため実コードを変更しない限り(@ts..などでのワーニング回避)コンパイル結果に影響は出ませんが、伴って変更した場合は動作に影響が出る恐れがあるので、既存のものはなるべく既存のまま通す方向で対応しています。
https://github.com/n-air-app/n-air-app/commit/5e14a69954274acd3107d2f20fd13b639f28e6ab

元々がおかしな扱いをしているため正しくしようとすると逆に問題になってしまう箇所などがいくつかあるのですが、勿論影響の無い範囲での変更は問題ないかと思います。

2023-06-26 16:36 UTC, koizuka commented on app/services/i18n/i18n.ts
> +  // @ts-ignore
古い方法である `@ts-ignore` ではなく `@ts-expect-error` に、という点はどうかな

2023-06-27 02:42 UTC, matsuyuki-a commented on app/services/i18n/i18n.ts
> +  // @ts-ignore
> これらは改修による変更に伴う際に回避したものではなく、tsconfig.jsonでのstrict系の設定変更において既存コードを極力変更しないように対応するため入れたものです。 strictではチェックの厳格化のみのため実コードを変更しない限り(@ts..などでのワーニング回避)コンパイル結果に影響は出ませんが、伴って変更した場合は動作に影響が出る恐れがあるので、既存のものはなるべく既存のまま通す方向で対応しています。 [5e14a69](https://github.com/n-air-app/n-air-app/commit/5e14a69954274acd3107d2f20fd13b639f28e6ab)
> 
> 元々がおかしな扱いをしているため正しくしようとすると逆に問題になってしまう箇所などがいくつかあるのですが、勿論影響の無い範囲での変更は問題ないかと思います。

承知しました。

2023-06-27 03:21 UTC, matsuyuki-a commented on app/services/i18n/i18n.ts
> +      const posMatch = (e as Error).message.match(/ at position ([0-9]+)$/);
このあたりの as Error は TypeScript アップデートで catch されるエラーの型が unknown になったためでしたね。
FailedResult の value を unknown にして NicoliveFailure の方でハンドリングできないか手元で消せないか試してみましたが自明じゃなかったのでまた次の機会でよさそうです(元々anyでしたしね)

2023-06-27 03:31 UTC, matsuyuki-a commented on app/services/nicolive-program/ParaphraseDictionary.test.ts
>      .map<[string, string]>((elem: replace_text) => [elem.text, elem.replacement]);
```ts 
 const table = replace_rules.elements
    .filter(isText)
    .map<[string, string]>((elem) => [elem.text, elem.replacement]);
```

で型通せそうです。

2023-06-27 03:40 UTC, matsuyuki-a approved these changes

2023-06-27 03:41 UTC, matsuyuki-a commented
いずれも軽微なので ✔️ しました 🙇

2023-06-29 07:05 UTC, koizuka commented on app/components/SourceSelector.vue.ts
> +  wasapi_process_output_capture: 'icon-display',
マージ後に別PRで対応することにします

2023-06-29 07:06 UTC, koizuka approved these changes

2023-06-29 07:08 UTC, merged